### ISSUE TITLE
[BUG]: Effort data is renamed 

### ISSUE THREAD

**Issue by ericward-noaa** [pfmc-assessments/indexwc#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Effort data seems to be renamed and drops the `_der` . I can hack this by using `dplyr::rename()` inside format_data(), but otherwise it throws an error

```
yt_data <- config |>
  dplyr::filter(species == "yellowtail rockfish") |>
  dplyr::rowwise() |>
  dplyr::mutate(
    data_raw = list(format_data(  dplyr::rename(eval(parse(text = fxn)), Area_swept_ha_der = Area_swept_ha)  )),
    data_filtered = list(data_raw |>
      dplyr::filter(
        depth <= min_depth, depth >= max_depth,
        latitude >= min_latitude, latitude <= max_latitude,
        year >= min_year, year <= max_year
      ))
  ) %>%
  dplyr::ungroup()
```

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by ericward-noaa** [comment]
Several ways to fix this, but one would be to just change the name in format_data(), like here

https://github.com/pfmc-assessments/indexwc/blob/7827cc90b5a0f8b498bd350a8006e28a6b63f671/R/format_data.R#L110

**Comment by kellijohnson-NOAA** [comment]
Thanks @ericward-noaa for noticing this. A change was made in {nwfscSurvey} [7 months ago](edf344998dff4c7a6436c7172fbd7826593f6b19) that I did not notice where two columns were renamed, date = date_formatted and Area_Swept_ha = area_swept_ha_der. I could not find date_formatted anywhere in this package and I found the one instance of areas_swept_ha_der and changed it to area_swept_ha_der because priot to that I use `tolower()` so I do not have to deal with all of the inconsistencies in case for column names. Thanks again for reporting this and sorry for the trouble.
