### ISSUE TITLE
[Feature]: Create indices for species to be assessed in 2023 

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [pfmc-assessments/indexwc#6]
### Describe the problem your feature request is related to.

At the September 2022 the PFMC made a final selection for assessments to be conducted in 2023. The species, assessment type, and potential model areas are are:

- Copper rockfish in California only, full assessment, separate models North and South Pt. Conception
- Canary rockfish (full assessment), coastwide model which may include areas
- Black rockfish (full assessment), state-based models
- Rex sole (length-based data-moderate), coastwide
- Shortspine thornyhead (length-based data-moderate), coastwide
- Petrale sole (update assessment), coastwide

Indices of abundance from the NWFSC WCGBT survey will need to be developed for species and areas with available information. Additionally, copper rockfish south of Pt. Conception will have an index developed from the NWFSC HKL survey. The below solutions focus only on indices from the NWFSC WCGBT survey.

### Describe the solution you'd like

Run sdmTMB and VAST to create indices of abundance using the three distributional options (gamma, lognormal, tweedie) for each species that assessors may select from. 

Species with a single NWFSC WCGT survey coastwide index with post-estimation stratification at a state level (default):
1. Petrale sole
2. Rex sole
3. Shortspine thornyhead

Species with limited data from the NWFSC WCGBT survey that index development should be explored:
1. Copper rockfish, split north and south of Pt. Conception

Species with multiple index options from the NWFSC WCGBT survey will be needed:
1. Canary rockfish 
a) coastwide with post-stratification by state
b) coastwide with post-stratification north and south of 42 degrees
c) three indices at state levels
d) two indices split north and south of 42 degrees

No data are available from either the NWFSC WCGBT or HKL survey for black rockfish

### Describe alternatives you have considered

If assessment authors need alternative indices to those indicated above the specific details could be submitted as a comment to this issue.

**Comment by kellijohnson-NOAA** [comment]
* For copper, is the split at Pt. Conception based on management or life history?
* For canary, would the index be coastwide with several post-stratifications or several spatio-temporal models using different splits?

cc
@brianlangseth-noaa, @melissamonk-noaa, @okenk, @iantaylor-noaa

**Comment by ericward-noaa** [comment]
On these splits, I assume index is being created for each region separately (running VAST / sdmTMB 2x). For data limited species, it might also be worth trying an index with spatial correlation parameters but different temporal trends. This would be as easy as fitting all the data in a single model, with the formula being something like `CPUE ~ fyear * region`, where region is a factor. The model with just year works too, but post-stratifying by region should give similar trends if spatiotemporal variation is small

**Comment by brianlangseth-NOAA** [comment]
The last review of canary noted that the previous WCGBTS index was very similar across areas. It was done coastwide and then post-processed to the state specific areas based on density maps. Our plan this year is to create each index by area, as opposed to a coastwide index, but to be frank, doing so will require us to do both. 

Thus, in your above post, options 1a and 1c. Splitting for CA and OR/WA is probably nice but is the lower priority imo. 

For canary the final distribution Jim used was a lognormal-ECE (extreme catch event). You've talked about this before. Is capability available for that yet?

**Comment by iantaylor-NOAA** [comment]
@kellijohnson-NOAA, you suggested emailing you info on which species need which indices, but the table below seems like a more useful format for folks to edit and expand on.
@okenk and @brianlangseth-NOAA can fill in more about Canary. I'm not sure who is the best point of contact for Rex and Shortspine.

### Which species need which indices?
Index | Species | Boundaries & splits| Notes
-- | -- | -- | -- 
WCGBTS | Petrale sole | coastwide, < 600 m | 
WCGBTS | Rex sole | coastwide | 
WCGBTS | Shortspine thornyhead | coastwide | 
WCGBTS | Copper rockfish | California only, split north and south of Pt. Conception
WCGBTS | Canary rockfish | multiple options | see top comment in this thread: https://github.com/kellijohnson-NOAA/indexwc/issues/6#issue-1388240746 for list of configurations options
Triennial | Petrale | TBD | was previously early vs late, @iantaylor-NOAA to provide info later
Triennial | Shortspine thornyhead | TBD | previously was two indices: shallow (55-366m from 1980-2004) and deep (366-500m from 1995-2004)
AKFSC Slope Survey | Shortspine thornyhead | coastwide | 
NWFSC Slope Survey | Shortspine thornyhead | coastwide | 
HKL | | |
Rec indices? | | |

**Comment by okenk** [comment]
For the pre-assessment workshop on 1/31, we would like a single coastwide index with a spatial prediction grid out to 350 meters depth. This may very well be the index we go with in the assessment, too.

Long-term we would like to explore options that generate three state indices. @brianlangseth-NOAA and I discussed, and it seems like there are three main options for this:
1. Fit one model and then post-stratify to get three indices by state. This minimizes boundary issues, but does induce correlation in the three indices since they come from one model. This was done in the previous assessment and produced three very similar indices which the STAR panel noted as a major uncertainty (see pfmc-assessments/canary_2023#4). Thus, we will probably need to produce something similar, but we will also need to explore other options. 
2. Three models, three indices. This avoids the correlation issue but introduces extra boundary effects.
3. @ericward-noaa's recommendation above to essentially split the difference between (1) and (2) and estimate year-state effects.

**Comment by kellijohnson-NOAA** [comment]
@okenk and @brianlangseth-NOAA what are your timeframes on when you desire an index? I was hoping to provide an updated index on the 17th but I am uncertain if I will fully understand the extreme catch event results by then.

@chantelwetzel-noaa for copper I am guessing that the addition of the index will be more of a sensitivity run rather than a base model so I have a bit more leeway as far as a timeline to explore the ECE distribution for you and Melissa right?

**Comment by chantelwetzel-noaa** [comment]
@kellijohnson-NOAA You are correct about the use of the wcgbt data for copper rockfish. I would only try to calculate an index south of Point Conception and even in this area the limited number of positive tows may not be viable.
